// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using QrOrder.Infrastructure.Data;

#nullable disable

namespace QrOrder.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612130234_AddOrderIdempotencyKey")]
    partial class AddOrderIdempotencyKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
